### ISSUE TITLE
Feature: Read All Tasks

### ISSUE THREAD

**Issue by obxpete** [obxpete/wits-365-summer-5782-project#1]
connect to db
read/write to DB

**Comment by obxpete** [comment]
review main branch baseline implementation

Add

**Comment by obxpete** [comment]
Add pagination to table

---- app.module.ts
// update imports here
import { MatPaginatorModule } from '@angular/material/paginator'  

// and here (imports array)
imports [ ...,, MatPaginatorModule] 

------- application.component.ts --------
  //paginator viewchild here
  @ViewChild(MatPaginator) paginator: MatPaginator;

  //ngAfterViewInit here
  ngAfterViewInit() {
    this.dataSource.paginator = this.paginator;
  }

 -------- application.component.html  --------

  <mat-paginator [pageSizeOptions]="[5, 10, 20]"
                 showFirstLastButtons 
                 aria-label="Select page of periodic elements">
  \</mat-paginator>

--- console ---
npm install

**Comment by obxpete** [comment]
I did this.

**Comment by shalvarishe** [comment]
I did this too

**Comment by RAlyeshmerni** [comment]
LGTM
